version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - backend
    volumes:
      - ./temp/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
#    env_file:
#      - ./.env
    ports:
      - "3200:3200"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

networks:
  backend:
    driver: bridge
